### PR TITLE
fix: Bring back `VisitMap` impl for std `HashSet`

### LINKED ISSUE #763: v0.8.0 `impl VisitMap for HashSet` breaking change
```
error[E0277]: the trait bound `HashSet<N, FxBuildHasher>: VisitMap<N>` is not satisfied
   --> crates/oxc_cfg/src/visit.rs:105:13
    |
105 |             dfs_visitor(graph, start, &mut visitor, discovered, finished, time),
    |             ^^^^^^^^^^^ the trait `VisitMap<N>` is not implemented for `HashSet<N, FxBuildHasher>`
    |
    = help: the following other types implement trait `VisitMap<N>`:
              `fixedbitset::FixedBitSet` implements `VisitMap<Ix>`
              `hashbrown::set::HashSet<N, S>` implements `VisitMap<N>`
note: required by a bound in `dfs_visitor`
   --> crates/oxc_cfg/src/visit.rs:122:8
    |
112 | fn dfs_visitor<G, M, F, C>(
    |    ----------- required by a bound in this function
...
122 |     M: VisitMap<G::NodeId>,
    |        ^^^^^^^^^^^^^^^^^^^ required by this bound in `dfs_visitor`

```

I am using `std::collections::HashSet`.

---

https://github.com/petgraph/petgraph/pull/747 made this change https://github.com/petgraph/petgraph/pull/747/files#diff-c4360dd06fc5c65c90d25ec01cef6d32381a3c1be22f5acfca1de66de272e60b

```diff
- use std::collections::HashSet;
+ use hashbrown::HashSet;
```

Not sure whether this is intentional or should be feature gated with `no_std` cc @bushrat011899

### PR DESCRIPTION
**Pull request by starovoid**
This fixes #763 .

### CODE REVIEW

File: src/visit/mod.rs [hunk 1]
```diff
@@ -444,6 +444,24 @@ where
     }
 }
 
+#[cfg(feature = "std")]
+impl<N, S> VisitMap<N> for std::collections::HashSet<N, S>
```
Comment (bushrat011899) [inline src/visit/mod.rs:448]: I don't really understand how this is considered a semver break, but I guess it is?

**Review by bushrat011899 — APPROVED** [review]
This is a good fix, but I'm not sure why this is considered a semver break.

File: src/visit/mod.rs (hunk 1 above)
Comment (starovoid) [reply src/visit/mod.rs:448]: This is most likely due to the `cargo-semver-checks` bug https://github.com/obi1kenobi/cargo-semver-checks/issues/1200

Comment (ABorgna) [reply src/visit/mod.rs:452]: Fixed now with #765.

For reference for the links pointing here, here's the error we had:
```
--- failure trait_newly_sealed: pub trait became sealed ---

Description:
A publicly-visible trait became sealed, so downstream crates are no longer able to implement it
        ref: https://rust-lang.github.io/api-guidelines/future-proofing.html#sealed-traits-protect-against-downstream-implementations-c-sealed
       impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.40.0/src/lints/trait_newly_sealed.ron

Failed in:
  trait petgraph::data::Create in file /home/runner/work/petgraph/petgraph/PR_BRANCH/src/data.rs:76
  trait petgraph::data::FromElements in file /home/runner/work/petgraph/petgraph/PR_BRANCH/src/data.rs:281
  trait petgraph::data::Build in file /home/runner/work/petgraph/petgraph/PR_BRANCH/src/data.rs:[53](https://github.com/petgraph/petgraph/actions/runs/14302765504/job/40080013218?pr=764#step:9:54)
```

https://github.com/petgraph/petgraph/actions/runs/14302765504/job/40080013218#step:9:52
